---

# == Notes ==

# GitLab automatically passes artifacts from previous stages by default

# This CI definition uses a GitLab provided include template

# == Includes ==

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

# == Global settings ==

stages:
  - 🧪 test
  - 📋 lint
  - 🏗 build
  - 🚚 publish

variables:
  APP_NAME: scar-add-metadata-toolbox

image:
  name: docker-registry.data.bas.ac.uk/magic/add-metadata-toolbox:latest
  entrypoint: [""]

default:
  before_script:
    - "ln -s /.venv .venv"
    - "poetry install --no-interaction --no-ansi"

# == Jobs ==

test:
  stage: 🧪 test
  needs: []
  variables:
    FLASK_ENV: testing
  script:
    - "poetry run pytest -o junit_family=xunit2 --junitxml=test-results.xml --random-order --cov=scar_add_metadata_toolbox --cov-config=.coveragerc --cov-fail-under=100 --cov-report=html"
  coverage: '/Total coverage: \d+\.\d+/'
  artifacts:
    when: always
    reports:
      junit: test-results.xml
    paths:
      - htmlcov
    expire_in: 1 month
  rules:
    - changes:
        - '**/*.py'

lint:
  stage: 📋 lint
  needs: []
  script:
    - "poetry check"
    - "poetry run flake8 src/ tests/"
    - "poetry export --without-hashes -f requirements.txt | poetry run safety check --full-report --stdin"
  rules:
    - changes:
        - '**/*.py'

build:
  stage: 🏗 build
  needs: []
  script:
    - "poetry version 0.0.0"
    - "poetry build"
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  rules:
    -
      if: '$CI_COMMIT_TAG == null'
      changes:
        - '**/*.py'

publish:
  stage: 🚚 publish
  needs:
    - test
    - lint
  before_script:
    - "ln -s /.venv .venv"
    - "poetry install --no-interaction --no-ansi"
    - 'poetry config repositories.gitlab "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/pypi"'
    - 'poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN" --local'
  script:
    - "poetry publish --build --no-interaction --repository gitlab"
  rules:
    - if: '$CI_COMMIT_TAG != null'
