# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=600"]
    - id: check-case-conflict
    - id: check-yaml
      # some VCR recordings contain PyYAML tags pre-commit doesn't understand, this checks syntax only
      args: [--unsafe]
    - id: check-toml  # for pyproject.toml
    - id: check-merge-conflict
    - id: trailing-whitespace
      exclude: \.pxd$
    - id: end-of-file-fixer
      exclude: \.pxd$
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.0
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/astral-sh/ty-pre-commit
  rev: v0.0.65
  hooks:
    - id: ty
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.12.0
  hooks:
    - id: uv-lock
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.39
  hooks:
      - id: pymarkdown
