# Safety Security and License Configuration file

# We recommend checking this file into your source control in the root of your Python project
# If this file is named .safety-policy.yml and is in the same directory where you run `safety check` it will be used
# by default. Otherwise, you can use the flag `safety check --policy-file <path-to-this-file>` to specify a custom
# location and name for the file. To validate and review your policy file, run the validate command:
# `safety validate policy_file --path <path-to-this-file>`

# Configuration for the `safety check` command
security:
    # A severity number between 0 and 10. Some helpful reference points: 9=ignore all vulnerabilities except CRITICAL severity. 7=ignore all vulnerabilities except CRITICAL & HIGH severity. 4=ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity.
    ignore-cvss-severity-below: 0

    ignore-cvss-unknown-severity: False  # True or False. We recommend you set this to False.

    # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities. We recommend you set this to False.
    continue-on-vulnerability-error: False

    # Here you can list multiple specific vulnerabilities you want to ignore/exempt (optionally for a time period)
    # We recommend making use of the optional `reason` and `expires` keys for each vulnerability that you ignore.
    ignore-vulnerabilities:
        51668:  # (PVE-2022-51668)
            reason: we don't believe we call this method, see MAGIC/add-metadata-toolbox#344 for details
            expires: '2025-01-01'
        51646:  # https://pyup.io/v/51646/f17 (CVE-2022-39174)
            reason: we don't believe we are vulnerable to this, see MAGIC/add-metadata-toolbox#329 for details
            expires: '2025-01-01'
        51645:  # https://pyup.io/v/51645/f17 (CVE-2022-39175)
            reason: we don't believe we are vulnerable to this, see MAGIC/add-metadata-toolbox#329 for details
            expires: '2025-01-01'
        51634:  # https://pyup.io/v/51634/f17 (PVE-2022-51634)
            reason: we don't believe we are vulnerable to this, see MAGIC/add-metadata-toolbox#329 for details
            expires: '2025-01-01'
        70612:  # https://data.safetycli.com/v/70612/f17/ (PVE-2022-51668)
            reason: we don't believe we call this method, see MAGIC/add-metadata-toolbox#372 for details
            expires: '2100-01-01'
        71636:  # https://data.safetycli.com/v/71636/f17 (CVE-2024-37568)
            reason: temporary exemption to unblock release until we can assess properly, see MAGIC/add-metadata-toolbox#377 for details
            expires: '2024-09-01'
        72260:  # https://data.safetycli.com/v/72260/52d (CVE-2024-40647)
            reason: temporary exemption to unblock merge until MAGIC/add-metadata-toolbox#380
            expires: '2024-08-08'
        72083: # https://data.safetycli.com/v/72083/52d (CVE-2024-39689)
          reason: temporary exemption to unblock merge until MAGIC/add-metadata-toolbox#380
          expires: '2024-08-08'

# Configuration for the `safety alert` command
#
# [Not Configured]
alert:
    security:
        # Configuration specific to Safety's GitHub Issue alerting
        github-issue:
            # Same as for security - these allow controlling if this alert will fire based on severity information
            # (default: not set)
            # ignore-cvss-severity-below: 6
            # ignore-cvss-unknown-severity: False

            # Add a label to pull requests with the cvss severity, if available (default: true)
            # label-severity: True

            # Add a label to pull requests, requires private repo permissions, even on public repos (default: security)
            # labels:
            #  - security

            # Assign users to pull requests, default is not set requires private repo permissions, even on public repos
            # (default: empty)
            # assignees:
            #  - example-user

            # Prefix to give issues when creating them. Note changing this might cause duplicate issues to be created
            # (default: "[PyUp] ")
            # issue-prefix: "[PyUp] "

        # Configuration specific to Safety's GitHub PR alerting
        github-pr:
            # Same as for security - these allow controlling if this alert will fire based on severity information
            # (default: not set)
            # ignore-cvss-severity-below: 6
            # ignore-cvss-unknown-severity: False

            # Set the default branch (ie, main, master)
            # (default: empty, the default branch on GitHub)
            branch: ''

            # Add a label to pull requests with the cvss severity, if available
            # default: true
            # label-severity: True

            # Add a label to pull requests, default is 'security'
            # requires private repo permissions, even on public repos
            # default: security
            # labels:
            #  - security

            # Assign users to pull requests, default is not set
            # requires private repo permissions, even on public repos
            # default: empty
            # assignees:
            #  - example-user

            # Configure the branch prefix for PRs created by this alert.
            # NB: Changing this will likely cause duplicate PRs.
            # (default: pyup/)
            branch-prefix: pyup/

            # Set a global prefix for PRs
            # (default: "[PyUp] ")
            pr-prefix: "[PyUp] "
