import os
from typing import TYPE_CHECKING

import pytest

from lantern.contrib.deployment_updates import entrypoint

if TYPE_CHECKING:
    from pathlib import Path

    from pytest_mock import MockerFixture

    from lantern.models.site import SiteEnvironment


class TestHealthExport:
    """Test deployment site updates contrib module."""

    @pytest.mark.vcr
    @pytest.mark.block_network
    @pytest.mark.parametrize("env", ["testing", "live"])
    def test_entrypoint(self, mocker: MockerFixture, tmp_path: Path, env: SiteEnvironment):
        """
        Can export site content.

        The VCR cassette for the live env contains all files generated by the outputs included by this module.
        That includes all site resources (css, etc.) and site pages which likely won't be sustainable to maintain.
        """
        os.environ["LANTERN_STORE_GITLAB_CACHE_PATH"] = str(tmp_path)
        # Rsync call for trusted content doesn't use requests etc. so not captured by VCR
        mock = mocker.MagicMock()
        mock.returncode = 0
        mocker.patch("sysrsync.runner.subprocess.run", return_value=mock)

        entrypoint(env=env)
