<?xml version='1.0' encoding='utf-8'?>
<!--
This is a derived version of the original xml-to-html-ISO.xsl stylesheet.

It inlines imports to produce a single stylesheet to allow easier processing.

======================================================================
	ISO 19115 and 19115-2 XML to HTML Stylesheet June 2011

	This is the XML Style sheet that displays metadata conforming to ISO 19115:2003(E) and ISO 19115-2:2009(E).
	This stylesheet can be applied to ISO XML to generate ISO HTML that includes a Header that displays the title
	of the resource as well as listing the main sections that the ISO metadata contains while linking to them.

	This file was generated by Altova MapForce 2009sp1

	Authors:
	This is the result of a collaboration of the Metadata Transform Working Group.
	For further information, please contact NOAA's National Coastal Data
	Development Center (NCDDC).
				National Coastal Data Development Center
				Toll Free: 866.732.2382
				E-mail: ncddcmetadata@noaa.gov

	Distribution Liability:
		NOAA makes no warranty regarding these data, expressed or implied,
		nor does the fact of distribution constitute such a warranty. NOAA, NESDIS,
		NODC and NCDDC cannot assume liability for any damages caused by any
		errors or omissions in these data, nor as a result of the failure of these data
		to function on a particular system. These files were developed for opensource uses.

	Use Constraints:
		The user is responsible for the results of any application of these stylsheets for other than its
		intended purpose. These stylesheets cannot guarantee valid output. Please feel free to edit
		stylesheet as needed for your organizations needs.

	Revisions:
		20111109 (JLM) Edited stylesheet to allow the title header to display for service metadata (19119)
		20120329 (JLM) Updated some element names to display correctly. Aslo added combined FC view.

-->
<!-- Top level directives -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gml="http://www.opengis.net/gml" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:exsl="http://exslt.org/common" extension-element-prefixes="exsl" version="1.0">
  <!--
Print the text of an XML element as preformatted text or wrapped paragraphs,
as appropriate. Makes the text readable on screen, and preserves the author's
intended formatting.

Created 6/20/06  Richard.Fozzard@noaa.gov

 @version $Id$

The stylesheet that imports this file needs to define two callback templates:
    printFormattedLine  Output a line, preserving all formatting (whitespace)
    printParagraphLine  Output a line as a continuous paragraph (word-wrapped)
both with the param "line", the one line string to print.

Each callback template then outputs the "line" string as desired (e.g. HTML,
text, XML). These templates can have some optional params which printFormatted
will pass through as needed:
    "restOfString"  Useful for doing something different at the end, e.g. no <P>
    "optional-param-1"  Useful for passing indent values
    "optional-param-2"  or word wrap widths...
    "optional-param-3"  or whatever...

Then, whenever a string of one or more lines needs to be output, call the
printFormatted template with the params:
    "elementContent"            a one or more line string to print
    "formattedSectionElement"   Name of element to wrap a sequence of formatted lines
                                    defaults to 'PRE', can be none, i.e. ''
    plus any of the desired optional params for the callbacks
-->
  <!--
  g-fold-width
    This parameter specifies the maximum length of a line when the
    formattedSectionElement (<pre> by default) is used. The browser
    may wrap PRE text at this width.
    [only works in Firefox 1+]
-->
  <!-- xsl:param name="g-fold-width" select="'80'"/ -->
  <!-- Whitespace characters -->
  <xsl:variable name="newline">
    <xsl:text>
</xsl:text>
  </xsl:variable>
  <xsl:variable name="tab">
    <xsl:text>	</xsl:text>
  </xsl:variable>
  <xsl:template name="printFormatted">
    <!-- string to print out -->
    <xsl:param name="elementContent"/>
    <!-- Name of element to wrap a sequence of formatted lines.
            Set to empty string for no element, i.e. plain text output. -->
    <xsl:param name="formattedSectionElement" select="'PRE'"/>
    <!-- used internally to skip 1 or more formatted lines -->
    <xsl:param name="skipFormattedLines" select="false()"/>
    <!-- if needed by callback template: -->
    <xsl:param name="optional-param-1"/>
    <xsl:param name="optional-param-2"/>
    <xsl:param name="optional-param-3"/>
    <xsl:if test="$elementContent">
      <!-- if not at end of string -->
      <xsl:variable name="containsNewline" select="contains($elementContent,$newline)"/>
      <xsl:variable name="firstLine">
        <xsl:call-template name="strip-trailing-whitespace">
          <xsl:with-param name="content">
            <xsl:choose>
              <xsl:when test="$containsNewline">
                <xsl:value-of select="substring-before($elementContent,$newline)"/>
              </xsl:when>
              <xsl:otherwise>
                <xsl:value-of select="$elementContent"/>
              </xsl:otherwise>
            </xsl:choose>
          </xsl:with-param>
        </xsl:call-template>
      </xsl:variable>
      <xsl:variable name="restOfString" select="substring-after($elementContent,$newline)"/>
      <!-- This line is formatted if it has 3 spaces or a tab or empty line -->
      <xsl:variable name="thisLineFormatted" select="$firstLine = '' or contains($firstLine,'   ') or contains($firstLine,$tab)"/>
      <xsl:choose>
        <!-- if a formatted line -->
        <xsl:when test="$thisLineFormatted = true()">
          <!-- if at start of a formatted section, and it's a non-empty line before the end of the element, print it -->
          <xsl:if test="not($skipFormattedLines) and (normalize-space($firstLine) or normalize-space($restOfString))">
            <xsl:choose>
              <!-- if specified, wrap a formatted section (1 or more lines) in an element -->
              <xsl:when test="$formattedSectionElement">
                <xsl:element name="{$formattedSectionElement}">
                  <xsl:attribute name="wrap"/>
                  <!-- works on Firefox 1.5+, not on IE 6/7, Safari 2 -->
                  <!-- xsl:attribute name="width"><xsl:value-of select="$g-fold-width"/></xsl:attribute -->
                  <xsl:call-template name="printFormattedSection">
                    <xsl:with-param name="elementContent" select="$elementContent"/>
                    <xsl:with-param name="optional-param-1" select="$optional-param-1"/>
                    <xsl:with-param name="optional-param-2" select="$optional-param-2"/>
                    <xsl:with-param name="optional-param-3" select="$optional-param-3"/>
                  </xsl:call-template>
                </xsl:element>
              </xsl:when>
              <!-- else if no element specified,
                            output a formatted section (1 or more lines) directly -->
              <xsl:otherwise>
                <xsl:call-template name="printFormattedSection">
                  <xsl:with-param name="elementContent" select="$elementContent"/>
                  <xsl:with-param name="optional-param-1" select="$optional-param-1"/>
                  <xsl:with-param name="optional-param-2" select="$optional-param-2"/>
                  <xsl:with-param name="optional-param-3" select="$optional-param-3"/>
                </xsl:call-template>
              </xsl:otherwise>
            </xsl:choose>
          </xsl:if>
          <!-- go to next line, recursively until next non-formatted line or end of string -->
          <xsl:call-template name="printFormatted">
            <xsl:with-param name="elementContent" select="$restOfString"/>
            <xsl:with-param name="formattedSectionElement" select="$formattedSectionElement"/>
            <xsl:with-param name="skipFormattedLines" select="true()"/>
            <xsl:with-param name="optional-param-1" select="$optional-param-1"/>
            <xsl:with-param name="optional-param-2" select="$optional-param-2"/>
            <xsl:with-param name="optional-param-3" select="$optional-param-3"/>
          </xsl:call-template>
        </xsl:when>
        <!-- else not a formatted line; treat as paragraph -->
        <xsl:otherwise>
          <!-- make callback to importing stylesheet to print the paragraph -->
          <xsl:call-template name="printParagraphLine">
            <xsl:with-param name="line" select="$firstLine"/>
            <xsl:with-param name="restOfString" select="$restOfString"/>
            <xsl:with-param name="optional-param-1" select="$optional-param-1"/>
            <xsl:with-param name="optional-param-2" select="$optional-param-2"/>
            <xsl:with-param name="optional-param-3" select="$optional-param-3"/>
          </xsl:call-template>
          <!-- go to next line, recursively until non-formatted line or end of string -->
          <xsl:call-template name="printFormatted">
            <xsl:with-param name="elementContent" select="$restOfString"/>
            <xsl:with-param name="formattedSectionElement" select="$formattedSectionElement"/>
            <xsl:with-param name="skipFormattedLines" select="false()"/>
            <xsl:with-param name="optional-param-1" select="$optional-param-1"/>
            <xsl:with-param name="optional-param-2" select="$optional-param-2"/>
            <xsl:with-param name="optional-param-3" select="$optional-param-3"/>
          </xsl:call-template>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:if>
  </xsl:template>
  <xsl:template name="printFormattedSection">
    <xsl:param name="elementContent"/>
    <!-- string to print out -->
    <!-- if needed by callback template: -->
    <xsl:param name="optional-param-1"/>
    <xsl:param name="optional-param-2"/>
    <xsl:param name="optional-param-3"/>
    <xsl:if test="$elementContent">
      <!-- if not at end of string -->
      <xsl:variable name="firstLine">
        <xsl:call-template name="strip-trailing-whitespace">
          <xsl:with-param name="content" select="substring-before($elementContent,$newline)"/>
        </xsl:call-template>
      </xsl:variable>
      <xsl:variable name="restOfString" select="substring-after($elementContent,$newline)"/>
      <!-- This line is formatted if it has 3 spaces or a tab or empty line -->
      <xsl:variable name="thisLineFormatted" select="$firstLine = '' or contains($firstLine,'   ') or contains($firstLine,$tab)"/>
      <xsl:if test="$thisLineFormatted = true()">
        <!-- if a formatted line -->
        <!-- make callback to importing stylesheet to print the formatted line -->
        <xsl:call-template name="printFormattedLine">
          <xsl:with-param name="line" select="$firstLine"/>
          <xsl:with-param name="restOfString" select="$restOfString"/>
          <xsl:with-param name="optional-param-1" select="$optional-param-1"/>
          <xsl:with-param name="optional-param-2" select="$optional-param-2"/>
          <xsl:with-param name="optional-param-3" select="$optional-param-3"/>
        </xsl:call-template>
        <!-- recursively call self until all formatted lines written -->
        <xsl:call-template name="printFormattedSection">
          <xsl:with-param name="elementContent" select="$restOfString"/>
          <xsl:with-param name="optional-param-1" select="$optional-param-1"/>
          <xsl:with-param name="optional-param-2" select="$optional-param-2"/>
          <xsl:with-param name="optional-param-3" select="$optional-param-3"/>
        </xsl:call-template>
      </xsl:if>
      <!-- do nothing and end recursion if we find a non-formatted, plain line -->
    </xsl:if>
  </xsl:template>
  <!--
  Strip the leading white space (including newlines or other characters
  that get translated to white space by normalize-space) from a block
  of text.

  [Stolen from somewhere on the web using Google.]
-->
  <xsl:template name="strip-leading-whitespace">
    <xsl:param name="content"/>
    <xsl:variable name="normalized-text" select="normalize-space($content)"/>
    <xsl:variable name="first-char" select="substring($normalized-text,1,1)"/>
    <xsl:variable name="leading-spaces" select="substring-before($content,$first-char)"/>
    <xsl:choose>
      <xsl:when test="string-length($leading-spaces) &gt; 0">
        <xsl:value-of select="substring-after($content,$leading-spaces)"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$content"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  <!--
  Strip the trailing white space (including newlines or other characters
  that get translated to white space by normalize-space) from a block
  of text.

  [Stolen from somewhere on the web using Google.]
-->
  <xsl:template name="strip-trailing-whitespace">
    <xsl:param name="content"/>
    <xsl:param name="i" select="string-length($content)"/>
    <xsl:choose>
      <xsl:when test="translate(substring($content, $i, 1), ' &#9;&#10;&#13;', '')">
        <xsl:value-of select="substring($content,1,$i)"/>
      </xsl:when>
      <xsl:when test="$i &lt; 2"/>
      <!-- done! -->
      <xsl:otherwise>
        <xsl:call-template name="strip-trailing-whitespace">
          <xsl:with-param name="content" select="$content"/>
          <xsl:with-param name="i" select="$i - 1"/>
        </xsl:call-template>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  <!--
Print an XML element as plain formatted text or wrapped paragraphs,
as appropriate. Makes the text readable on screen, and preserves the author's
intended formatting.

[The 'fold' and 'chop' templates come from original xml-to-text.xsl by Joe
Shirley.]

Created 6/20/06  Richard.Fozzard@noaa.gov

 @version $Id$

This file defines two callback templates used by printFormatted.xsl:
    printFormattedLine  Output a line, preserving all formatting (whitespace)
    printParagraphLine  Output a line as a continuous paragraph (word-wrapped)

-->
  <!--
  g-fold-width
    This parameter specifies the maximum length of a line when the
    'fold' text formatting option is chosen. This parameter is ignored
    for other text formatting options.
-->
  <xsl:param name="g-fold-width" select="'80'"/>
  <!--
  g-fold-character
    This parameter specifies where a line may be broken when the
    'fold' text formatting option is chosen. This parameter is ignored
    for other text formatting options.
-->
  <xsl:param name="g-fold-character" select="' '"/>
  <!-- Output a single line formatted with all white space preserved. Indent each line
  to the current indent level.
-->
  <xsl:template name="printFormattedLine">
    <xsl:param name="line"/>
    <xsl:param name="restOfString"/>
    <xsl:param name="optional-param-1"/>
    <xsl:variable name="indent" select="$optional-param-1"/>
    <!-- Print next line, unless it's a blank line after final text line. -->
    <xsl:if test="(string-length($line) &gt; 0) or (string-length(normalize-space($restOfString)) &gt; 0)">
      <xsl:value-of select="$indent"/>
      <xsl:value-of select="$line"/>
      <xsl:value-of select="$newline"/>
    </xsl:if>
  </xsl:template>
  <!-- Output a single line formatted as a word-wrapped paragraph. Indent each line
  to the current indent level. Use 'fold' template to do the word-wrapping.
-->
  <xsl:template name="printParagraphLine">
    <xsl:param name="line"/>
    <xsl:param name="restOfString"/>
    <xsl:param name="optional-param-1"/>
    <xsl:param name="optional-param-2"/>
    <xsl:variable name="indent" select="$optional-param-1"/>
    <xsl:variable name="length" select="$optional-param-2"/>
    <!-- Print line with 'fold', unless it's a blank line after final text line. -->
    <xsl:if test="(string-length($line) &gt; 0) or (string-length(normalize-space($restOfString)) &gt; 0)">
      <xsl:value-of select="$indent"/>
      <!-- fold doesn't indent first line -->
      <xsl:call-template name="fold">
        <xsl:with-param name="original-string" select="normalize-space($line)"/>
        <xsl:with-param name="length" select="$length"/>
        <xsl:with-param name="indent" select="$indent"/>
      </xsl:call-template>
    </xsl:if>
  </xsl:template>
  <!--
  Text formatting template. Create line breaks. Indent each line to
  the current indent level. Return the next line each time the
  template is called.
-->
  <xsl:template name="fold">
    <xsl:param name="original-string"/>
    <xsl:param name="length"/>
    <xsl:param name="indent"/>
    <xsl:param name="fold-width" select="$g-fold-width"/>
    <xsl:variable name="printstring">
      <xsl:choose>
        <xsl:when test="string-length($original-string) &gt; number($length)">
          <!-- Text is longer than max, chop it down and print next line. -->
          <xsl:call-template name="chop">
            <xsl:with-param name="newstring" select="''"/>
            <xsl:with-param name="original-string" select="$original-string"/>
            <xsl:with-param name="length" select="$length"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="$original-string"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:value-of select="$printstring"/>
    <xsl:value-of select="$newline"/>
    <xsl:variable name="str" select="substring-after($original-string, $printstring)"/>
    <xsl:if test="string-length($str)">
      <!-- More text, call fold recursively. -->
      <xsl:value-of select="$indent"/>
      <xsl:call-template name="fold">
        <xsl:with-param name="original-string" select="$str"/>
        <xsl:with-param name="length" select="number($fold-width) - string-length($indent)"/>
        <xsl:with-param name="indent" select="$indent"/>
      </xsl:call-template>
    </xsl:if>
  </xsl:template>
  <!--
  Create line breaks. Break only at specified line break
  character. If possible keep lines less than a specified maximum
  length, otherwise break at first acceptable character after
  maximum length. Return one line each time the template is called.
-->
  <xsl:template name="chop">
    <xsl:param name="newstring"/>
    <xsl:param name="original-string"/>
    <xsl:param name="char" select="$g-fold-character"/>
    <xsl:param name="length"/>
    <xsl:variable name="str1">
      <!-- str1 is the part before the break. -->
      <xsl:choose>
        <xsl:when test="contains($original-string, $char)">
          <!-- The text contains a break character, chop it off. -->
          <xsl:value-of select="concat($newstring, substring-before($original-string, $char), $char)"/>
        </xsl:when>
        <xsl:otherwise>
          <!-- The text contains no break character, use it all. -->
          <xsl:value-of select="concat($newstring, $original-string)"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:variable name="str2">
      <!-- str2 is the part after the break. -->
      <xsl:choose>
        <xsl:when test="contains($original-string, $char)">
          <!-- The text contains a break character, take what is after that. -->
          <xsl:value-of select="substring-after($original-string, $char)"/>
        </xsl:when>
        <xsl:otherwise>
          <!-- The text contains no break character, use an empty string. -->
          <xsl:value-of select="''"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:choose>
      <xsl:when test="(string-length($str1) &lt; number($length)) and $str2">
        <xsl:variable name="return-value">
          <xsl:call-template name="chop">
            <xsl:with-param name="newstring" select="$str1"/>
            <xsl:with-param name="original-string" select="$str2"/>
            <xsl:with-param name="char" select="$char"/>
            <xsl:with-param name="length" select="$length"/>
          </xsl:call-template>
        </xsl:variable>
        <xsl:value-of select="$return-value"/>
      </xsl:when>
      <xsl:when test="$newstring">
        <xsl:value-of select="$newstring"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$str1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  <!--
	Created: Sept 15, 2009, AMilan -
	Used to display content of tags and test for @nilReason, @indeterminatePosition, replace single quotes and endash
	-->
  <xsl:strip-space elements="*"/>
  <xsl:param name="singleQuote">'</xsl:param>
  <xsl:param name="rightQuote">’</xsl:param>
  <xsl:param name="enDash">–</xsl:param>
  <xsl:param name="normalDash">-</xsl:param>
  <xsl:template name="displayElement" match="/">
    <xsl:variable name="value">
      <xsl:choose>
        <xsl:when test="contains(normalize-space(.),$singleQuote)">
          <xsl:variable name="value1">
            <xsl:value-of select="translate(normalize-space(.), $singleQuote, $rightQuote)"/>
          </xsl:variable>
          <xsl:choose>
            <xsl:when test="contains($value1,$enDash)">
              <xsl:value-of select="translate($value1, $enDash, $normalDash)"/>
            </xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="$value1"/>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:when>
        <xsl:when test="contains(normalize-space(.),$enDash)">
          <xsl:value-of select="translate(normalize-space(.), $enDash, $normalDash)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="normalize-space(.)"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:choose>
      <xsl:when test="./@gco:nilReason"> (<xsl:value-of select="local-name(.)"/><xsl:text> is </xsl:text><xsl:value-of select="./@gco:nilReason"/>) </xsl:when>
      <xsl:when test="./@indeterminatePosition">
        <xsl:value-of select="./@indeterminatePosition"/>
        <xsl:text> </xsl:text>
        <xsl:value-of select="$value"/>
      </xsl:when>
      <xsl:when test="./@xlink:href"> &lt;a href="<xsl:value-of select="normalize-space(./@xlink:href)"/><xsl:value-of select="normalize-space(./@xlink:href)"/></xsl:when>
      <xsl:when test="./gco:Boolean">
        <xsl:if test="./gco:Boolean='false'">No</xsl:if>
        <xsl:if test="./gco:Boolean='true'">Yes</xsl:if>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$value"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  <xsl:output method="html" indent="no"/>
  <!-- Global parameters -->
  <!--
  g-tag-translation-URI
    This parameter specifies the URI of the external document
    containing the lookup table for the tag name translation. The
    default is the name of a file in the same directory as the
    stylesheet. Make sure this is a network accessible URI if
    delivering to a browser for translation.
-->
  <xsl:param name="g-tag-translation-URI" select="'elements-ISO.xml'"/>
  <xsl:param name="g-header-translation-URI" select="'headers-ISO.xml'"/>
  <!--
  g-indent-increment
    This parameter specifies the character string to be added before a
    label for each level of indentation. I.e. if you want each level
    indented by four spaces, then make this a four space character
    string. Set this to the empty string to forego indenting.
-->
  <xsl:param name="g-indent-increment" select="'  '"/>
  <!--
  g-fold-width
    This parameter specifies the maximum length of a line when
    word-wrapping lines. It must match the value specified in
    printTextLines.xsl.
-->
  <xsl:param name="g-fold-width" select="'120'"/>
  <!--
  g-text-field-handler
    This parameter specifies the handler to use for formatting text
    fields. The choices are 'fold' to fold lines at a maximum length
    and 'print-lines' to print lines with line breaks preserved as in
    the source XML document. If unspecified, or if an invalid choice
    is specified, 'print-lines' will be used.

  [OBSOLETE: replaced by printFormatted template]
-->
  <xsl:param name="g-text-field-handler" select="'print-lines'"/>
  <!-- Get the g-tag-translation-URI (elements.xml) node-set just once.
    This should improve performance on large XML files.
    This also works around a memory-leak problem using JSTL \<x:transform xsltSystemId
    (the memory-leak may also be present in direct Transformer calls from Java).
    /// We see this in Xalan 2.6.0; is it fixed in 2.7.0 ?
-->
  <xsl:variable name="g-tag-translations">
    <names>
      <name tagname="gmd:abstract">Abstract</name>
      <name tagname="gmd:accessConstraints">Access constraints</name>
      <name tagname="gmd:address">Address</name>
      <name tagname="gmd:administrativeArea">Administrative area</name>
      <name tagname="gmd:aggregateDataSetIdentifier">Aggregate Data Set Identifier</name>
      <name tagname="gmd:aggregateDataSetName">Aggregate Data Set Name</name>
      <name tagname="gmd:aggregationInfo">Aggregation Info</name>
      <name tagname="gmd:alternateTitle">Alternate title</name>
      <name tagname="gmd:amendmentNumber">Amendment number</name>
      <name tagname="gmd:applicationProfile">Application profile</name>
      <name tagname="gmd:applicationSchemaInfo">Application schema info</name>
      <name tagname="gmd:associationType">Association Type</name>
      <name tagname="gmd:attributeDescription">Attribute description</name>
      <name tagname="gmd:attributeInstances">Attribute instances</name>
      <name tagname="gmd:attributes">Attributes</name>
      <name tagname="gmd:authority">Authority</name>
      <name tagname="gmd:axisDimensionProperties">Axis Dimension Properties</name>
      <name tagname="gmd:bitsPerValue">Bits per value</name>
      <name tagname="gmd:cameraCalibrationInformationAvailability">Camera calibration information availability</name>
      <name tagname="gmd:cellGeometry">Cell geometry</name>
      <name tagname="gmd:centerPoint">Center point</name>
      <name tagname="gmd:characterEncoding">Character Encoding</name>
      <name tagname="gmd:characterSet">Character set</name>
      <name tagname="gmd:checkPointAvailability">Check point availability</name>
      <name tagname="gmd:checkPointDescription">Check point description</name>
      <name tagname="gmd:CI_Address">Address</name>
      <name tagname="gmd:CI_Citation">Citation</name>
      <name tagname="gmd:CI_Contact">Contact</name>
      <name tagname="gmd:CI_Date">Date</name>
      <name tagname="gmd:CI_DateTypeCode">Date type code</name>
      <name tagname="gmd:CI_OnLineFunctionCode">Online function code</name>
      <name tagname="gmd:CI_OnlineResource">Online Resource</name>
      <name tagname="gmd:CI_PresentationFormCode">Presentation form code</name>
      <name tagname="gmd:CI_ResponsibleParty">Responsible party</name>
      <name tagname="gmd:CI_RoleCode">Role code</name>
      <name tagname="gmd:CI_Series">Series</name>
      <name tagname="gmd:CI_Telephone">Telephone</name>
      <name tagname="gmd:citation">Citation</name>
      <name tagname="gmd:citedResponsibleParty">Cited responsible party</name>
      <name tagname="gmd:city">City</name>
      <name tagname="gmd:classification">Classification</name>
      <name tagname="gmd:classificationSystem">Classification system</name>
      <name tagname="gmd:cloudCoverPercentage">Cloud cover percentage</name>
      <name tagname="gmd:code">Code</name>
      <name tagname="gmd:codeSpace">Code Space</name>
      <name tagname="gmd:collectiveTitle">Collective title</name>
      <name tagname="gmd:complianceCode">Compliance code</name>
      <name tagname="gmd:composedOf">Composed of</name>
      <name tagname="gmd:compressionGenerationQuantity">Compression generation quantity</name>
      <name tagname="gmd:condition">Condition</name>
      <name tagname="gmd:constraintLanguage">Constraint language</name>
      <name tagname="gmd:contact">Metadata author</name>
      <name tagname="gmd:contact">Metadata author</name>
      <name tagname="gmd:contactInfo">Contact info</name>
      <name tagname="gmd:contactInstructions">Contact instructions</name>
      <name tagname="gmd:contentInfo">Content info</name>
      <name tagname="gmd:contentType">Content type</name>
      <name tagname="gmd:controlPointAvailability">Control point availability</name>
      <name tagname="gmd:cornerPoints">Corner points</name>
      <name tagname="gmd:Country">Country</name>
      <name tagname="gmd:country">Country</name>
      <name tagname="gmd:country">Country</name>
      <name tagname="gmd:credit">Credit</name>
      <name tagname="gmd:dataQualityInfo">Data quality info</name>
      <name tagname="gmd:dataset">Dataset Set</name>
      <name tagname="gmd:dataSetURI">Dataset URI</name>
      <name tagname="gmd:dataType">Data type</name>
      <name tagname="gmd:date">Date</name>
      <name tagname="gmd:dateOfNextUpdate">Date of next update</name>
      <name tagname="gmd:dateStamp">Date stamp</name>
      <name tagname="gmd:dateTime">Date and time</name>
      <name tagname="gmd:dateType">Date type</name>
      <name tagname="gmd:definition">Definition</name>
      <name tagname="gmd:deliveryPoint">Delivery point</name>
      <name tagname="gmd:denominator">Denominator</name>
      <name tagname="gmd:density">Density</name>
      <name tagname="gmd:densityUnits">Density units</name>
      <name tagname="gmd:describes">Describes</name>
      <name tagname="gmd:description">Description</name>
      <name tagname="gmd:descriptiveKeywords">Descriptive keywords</name>
      <name tagname="gmd:descriptor">Descriptor</name>
      <name tagname="gmd:dimension">Dimension</name>
      <name tagname="gmd:dimensionName">Dimension name</name>
      <name tagname="gmd:dimensionSize">Dimension size</name>
      <name tagname="gmd:distance">Distance</name>
      <name tagname="gmd:distributionFormat">Distribution format</name>
      <name tagname="gmd:distributionInfo">Distribution info</name>
      <name tagname="gmd:distributionOrderProcess">Distribution Order Process</name>
      <name tagname="gmd:distributor">Distributor</name>
      <name tagname="gmd:distributorContact">Distributor contact</name>
      <name tagname="gmd:distributorFormat">Distributor format</name>
      <name tagname="gmd:distributorTransferOptions">Distributor transfer options</name>
      <name tagname="gmd:domainCode">Domain code</name>
      <name tagname="gmd:domainOfValidity">Domain of validity</name>
      <name tagname="gmd:domainValue">Domain value</name>
      <name tagname="gmd:DQ_AbsoluteExternalPositionalAccuracy">Absolute external positional accuracy</name>
      <name tagname="gmd:DQ_AccuracyOfATimeMeasurement">Accuracy of time measurement</name>
      <name tagname="gmd:DQ_CompletenessCommission">Completeness commission</name>
      <name tagname="gmd:DQ_CompletenessOmission">Completeness omission</name>
      <name tagname="gmd:DQ_ConceptualConsistency">Conceptual consistency</name>
      <name tagname="gmd:DQ_ConformanceResult">Conformance result</name>
      <name tagname="gmd:DQ_DataQuality">Data quality</name>
      <name tagname="gmd:DQ_DomainConsistency">Domain consistency</name>
      <name tagname="gmd:DQ_EvaluationMethodTypeCode">Evaluation method type code</name>
      <name tagname="gmd:DQ_FormatConsistency">Format consistency</name>
      <name tagname="gmd:DQ_GriddedDataPositionalAccuracy">Gridded data positional accuracy</name>
      <name tagname="gmd:DQ_NonQuantitativeAttributeAccuracy">Non quantitative attribute accuracy</name>
      <name tagname="gmd:DQ_QuantitativeAttributeAccuracy">Quantitative attribute accuracy</name>
      <name tagname="gmd:DQ_QuantitativeResult">Quantitative result</name>
      <name tagname="gmd:DQ_RelativeInternalPositionalAccuracy">Relative internal positional accuracy</name>
      <name tagname="gmd:DQ_Scope">Scope</name>
      <name tagname="gmd:DQ_TemporalConsistency">Temporal consistency</name>
      <name tagname="gmd:DQ_TemporalValidity">Temporal validity</name>
      <name tagname="gmd:DQ_ThematicClassificationCorrectness">Thematic classification correctness</name>
      <name tagname="gmd:DQ_TopologicalConsistency">Topological consistency</name>
      <name tagname="gmd:DS_Association">Association</name>
      <name tagname="gmd:DS_AssociationTypeCode">Association type code</name>
      <name tagname="gmd:DS_AssociationTypeCode">Association type code</name>
      <name tagname="gmd:DS_DataSet">DataSet</name>
      <name tagname="gmd:DS_Initiative">Initiative</name>
      <name tagname="gmd:DS_InitiativeTypeCode">Initiative type code</name>
      <name tagname="gmd:DS_OtherAggregate">Other Aggregate</name>
      <name tagname="gmd:DS_Platform">Platform</name>
      <name tagname="gmd:DS_ProductionSeries">Production Series</name>
      <name tagname="gmd:DS_Sensor">Sensor</name>
      <name tagname="gmd:DS_Series">Series</name>
      <name tagname="gmd:DS_StereoMate">Stereo Mate</name>
      <name tagname="gmd:eastBoundLongitude">East bound longitude</name>
      <name tagname="gmd:edition">Edition</name>
      <name tagname="gmd:editionDate">Edition date</name>
      <name tagname="gmd:electronicMailAddress">Electronic mail address</name>
      <name tagname="gmd:environmentDescription">Environment description</name>
      <name tagname="gmd:equivalentScale">Equivalent scale</name>
      <name tagname="gmd:errorStatistic">Error statistic</name>
      <name tagname="gmd:evaluationMethodDescription">Evaluation method description</name>
      <name tagname="gmd:evaluationMethodType">Evaluation method type code</name>
      <name tagname="gmd:evaluationProcedure">Evaluation procedure</name>
      <name tagname="gmd:EX_BoundingPolygon">BoundingPolygon</name>
      <name tagname="gmd:EX_Extent">Extent</name>
      <name tagname="gmd:EX_GeographicBoundingBox">Geographic bounding box</name>
      <name tagname="gmd:EX_GeographicDescription">Geographic description</name>
      <name tagname="gmd:EX_SpatialTemporalExtent">Spatial Temporal Extent</name>
      <name tagname="gmd:EX_TemporalExtent">Temporal extent</name>
      <name tagname="gmd:EX_VerticalExtent">Vertical extent</name>
      <name tagname="gmd:explanation">Explanation</name>
      <name tagname="gmd:extendedElementInformation">Extended element information</name>
      <name tagname="gmd:extensionOnLineResource">Extension Online resource</name>
      <name tagname="gmd:extent">Extent</name>
      <name tagname="gmd:extentTypeCode">Extent type code</name>
      <name tagname="gmd:facsimile">Facsimile</name>
      <name tagname="gmd:featureAttribute">Feature Attribute</name>
      <name tagname="gmd:featureCatalogueCitation">Feature catalogue citation</name>
      <name tagname="gmd:featureInstances">Feature instances</name>
      <name tagname="gmd:features">Features</name>
      <name tagname="gmd:featureType">FeatureType</name>
      <name tagname="gmd:featureTypes">Feature types</name>
      <name tagname="gmd:fees">Fees</name>
      <name tagname="gmd:fileDecompressionTechnique">File decompression technique</name>
      <name tagname="gmd:fileDescription">File description</name>
      <name tagname="gmd:fileIdentifier">File identifier</name>
      <name tagname="gmd:fileName">File name</name>
      <name tagname="gmd:fileType">File type</name>
      <name tagname="gmd:filmDistortionInformationAvailability">Film distortion information availability</name>
      <name tagname="gmd:formatDistributor">Format distributor</name>
      <name tagname="gmd:function">Function</name>
      <name tagname="gmd:geographicElement">Geographic element</name>
      <name tagname="gmd:geographicIdentifier">Geographic identifier</name>
      <name tagname="gmd:geometricObjectCount">Geometric object count</name>
      <name tagname="gmd:geometricObjects">Geometric objects</name>
      <name tagname="gmd:geometricObjectType">Geometric object type</name>
      <name tagname="gmd:georeferencedParameters">Georeferenced Parameters</name>
      <name tagname="gmd:graphicOverview">Graphic overview</name>
      <name tagname="gmd:graphicsFile">Graphics file</name>
      <name tagname="gmd:handlingDescription">Handling description</name>
      <name tagname="gmd:has">has</name>
      <name tagname="gmd:hierarchyLevel">Hierarchy level</name>
      <name tagname="gmd:hierarchyLevelName">Hierarchy level name</name>
      <name tagname="gmd:hoursOfService">Hours of service</name>
      <name tagname="gmd:identificationInfo">Identification info</name>
      <name tagname="gmd:identifier">Identifier</name>
      <name tagname="gmd:illuminationAzimuthAngle">Illumination azimuth angle</name>
      <name tagname="gmd:illuminationElevationAngle">Illumination elevation angle</name>
      <name tagname="gmd:imageQualityCode">Image quality code</name>
      <name tagname="gmd:imagingCondition">Imaging condition</name>
      <name tagname="gmd:includedWithDataset">Included with dataset</name>
      <name tagname="gmd:individualName">Individual name</name>
      <name tagname="gmd:initiativeType">Initiative Type</name>
      <name tagname="gmd:ISBN">ISBN</name>
      <name tagname="gmd:ISSN">ISSN</name>
      <name tagname="gmd:issueIdentification">Issue identification</name>
      <name tagname="gmd:keyword">Keyword</name>
      <name tagname="gmd:language">Language</name>
      <name tagname="gmd:LanguageCode">Language Code</name>
      <name tagname="gmd:languageCode">Language code</name>
      <name tagname="gmd:lensDistortionInformationAvailability">Lens distortion information availability</name>
      <name tagname="gmd:level">Hierarchy level</name>
      <name tagname="gmd:levelDescription">Level description</name>
      <name tagname="gmd:LI_Lineage">Lineage</name>
      <name tagname="gmd:LI_ProcessStep">Process step</name>
      <name tagname="gmd:LI_Source">Source</name>
      <name tagname="gmd:lineage">Lineage</name>
      <name tagname="gmd:linkage">Linkage</name>
      <name tagname="gmd:locale">Locale</name>
      <name tagname="gmd:LocalisedCharacterString">Localised Character String</name>
      <name tagname="gmd:localisedString">Localised String</name>
      <name tagname="gmd:maintenanceAndUpdateFrequency">Maintenance and update frequency</name>
      <name tagname="gmd:maintenanceNote">Maintenance note</name>
      <name tagname="gmd:maximumOccurrence">Maximum occurrence</name>
      <name tagname="gmd:maximumValue">Maximum value</name>
      <name tagname="gmd:maxValue">Maximum value</name>
      <name tagname="gmd:MD_AggregateInformation">AggregateInformation</name>
      <name tagname="gmd:MD_ApplicationSchemaInformation">Application schema info</name>
      <name tagname="gmd:MD_Band">Band</name>
      <name tagname="gmd:MD_BrowseGraphic">BrowseGraphic</name>
      <name tagname="gmd:MD_CellGeometryCode">Cell geometry code</name>
      <name tagname="gmd:MD_CharacterSetCode">Character set code</name>
      <name tagname="gmd:MD_ClassificationCode">Classification code</name>
      <name tagname="gmd:MD_Constraints">Constraints</name>
      <name tagname="gmd:MD_CoverageContentTypeCode">Content type code</name>
      <name tagname="gmd:MD_CoverageDescription">Coverage description</name>
      <name tagname="gmd:MD_DataIdentification">Data identification</name>
      <name tagname="gmd:MD_DatatypeCode">Data type code</name>
      <name tagname="gmd:MD_DigitalTransferOptions">Digital transfer options</name>
      <name tagname="gmd:MD_Dimension">Dimension</name>
      <name tagname="gmd:MD_DimensionNameTypeCode">Dimension name type code</name>
      <name tagname="gmd:MD_Distribution">Distribution</name>
      <name tagname="gmd:MD_DistributionUnits">DistributionUnits</name>
      <name tagname="gmd:MD_Distributor">Distributor</name>
      <name tagname="gmd:MD_ExtendedElementInformation">Extended elemen information</name>
      <name tagname="gmd:MD_FeatureCatalogueDescription">Feature catalogue description</name>
      <name tagname="gmd:MD_Format">Format</name>
      <name tagname="gmd:MD_GeometricObjects">Geometric objects</name>
      <name tagname="gmd:MD_GeometricObjectTypeCode">Geometric object type code</name>
      <name tagname="gmd:MD_Georectified">Georectified</name>
      <name tagname="gmd:MD_Georeferenceable">Georeferenceable</name>
      <name tagname="gmd:MD_GridSpatialRepresentation">Grid spatial representation</name>
      <name tagname="gmd:MD_Identifier">Identifier</name>
      <name tagname="gmd:MD_ImageDescription">Image description</name>
      <name tagname="gmd:MD_ImagingConditionCode">Imaging condition code</name>
      <name tagname="gmd:MD_Keywords">Keywords</name>
      <name tagname="gmd:MD_KeywordTypeCode">Keyword type code</name>
      <name tagname="gmd:MD_LegalConstraints">Legal constraints</name>
      <name tagname="gmd:MD_MaintenanceFrequencyCode">Maintenance frequency code</name>
      <name tagname="gmd:MD_MaintenanceInformation">Maintenance information</name>
      <name tagname="gmd:MD_Medium">Medium</name>
      <name tagname="gmd:MD_MediumFormatCode">Medium format</name>
      <name tagname="gmd:MD_MediumNameCode">Medium name code</name>
      <name tagname="gmd:MD_Metadata">Metadata</name>
      <name tagname="gmd:MD_MetadataExtensionInformation">Metadata extension info</name>
      <name tagname="gmd:MD_ObligationCode">Obligation code</name>
      <name tagname="gmd:MD_PixelOrientationCode">Pixel orientation code</name>
      <name tagname="gmd:MD_PortrayalCatalogueReference">Portrayal catalogue reference</name>
      <name tagname="gmd:MD_ProgressCode">Progress code</name>
      <name tagname="gmd:MD_RangeDimension">Range dimension</name>
      <name tagname="gmd:MD_ReferenceSystem">Reference system</name>
      <name tagname="gmd:MD_RepresentativeFraction">Representative fraction</name>
      <name tagname="gmd:MD_Resolution">Resolution</name>
      <name tagname="gmd:MD_RestrictionCode">Restriction code</name>
      <name tagname="gmd:MD_ScopeCode">Scope code</name>
      <name tagname="gmd:MD_ScopeDescription">Scope description</name>
      <name tagname="gmd:MD_SecurityConstraints">Security constraints</name>
      <name tagname="gmd:MD_ServiceIdentification">MD Service identification</name>
      <name tagname="gmd:MD_ServiceIdentification">Service identification</name>
      <name tagname="gmd:MD_SpatialRepresentationTypeCode">Spatial representation type code</name>
      <name tagname="gmd:MD_StandardOrderProcess">Standard order process</name>
      <name tagname="gmd:MD_TopicCategoryCode">Topic category code</name>
      <name tagname="gmd:MD_TopologyLevelCode">Topology level code</name>
      <name tagname="gmd:MD_Usage">Usage</name>
      <name tagname="gmd:MD_VectorSpatialRepresentation">Vector spatial representation</name>
      <name tagname="gmd:measureDescription">Measure description</name>
      <name tagname="gmd:measureIdentification">Measure identification</name>
      <name tagname="gmd:mediumFormat">Medium format</name>
      <name tagname="gmd:mediumNote">Medium note</name>
      <name tagname="gmd:metadataConstraints">Metadata constraints</name>
      <name tagname="gmd:metadataExtensionInfo">Metadata extension info</name>
      <name tagname="gmd:metadataMaintenance">Metadata maintenance</name>
      <name tagname="gmd:metadataStandardName">Metadata standard name</name>
      <name tagname="gmd:metadataStandardVersion">Metadata standard version</name>
      <name tagname="gmd:minimumValue">Minimum value</name>
      <name tagname="gmd:minValue">Minimum value</name>
      <name tagname="gmd:name">Name</name>
      <name tagname="gmd:nameOfMeasure">Name of measure</name>
      <name tagname="gmd:northBoundLatitude">North bound latitude</name>
      <name tagname="gmd:numberOfDimensions">Number of dimensions</name>
      <name tagname="gmd:obligation">Obligation</name>
      <name tagname="gmd:offLine">Offline</name>
      <name tagname="gmd:offset">Offset</name>
      <name tagname="gmd:onLine">Online</name>
      <name tagname="gmd:onlineResource">Online Resource</name>
      <name tagname="gmd:orderingInstructions">Ordering instructions</name>
      <name tagname="gmd:organisationName">Organisation name</name>
      <name tagname="gmd:orientationParameterAvailability">Orientation parameter availability</name>
      <name tagname="gmd:orientationParameterDescription">Orientation parameter description</name>
      <name tagname="gmd:other">Other</name>
      <name tagname="gmd:otherCitationDetails">Other citation details</name>
      <name tagname="gmd:otherConstraints">Other constraints</name>
      <name tagname="gmd:page">Page</name>
      <name tagname="gmd:parameterCitation">Parameter citation</name>
      <name tagname="gmd:parentEntity">Parent entity</name>
      <name tagname="gmd:parentIdentifier">Parent identifier</name>
      <name tagname="gmd:partOf">part of</name>
      <name tagname="gmd:pass">Pass</name>
      <name tagname="gmd:peakResponse">Peak response</name>
      <name tagname="gmd:phone">Phone</name>
      <name tagname="gmd:plannedAvailableDateTime">Planned available date and time</name>
      <name tagname="gmd:pointInPixel">Point in pixel</name>
      <name tagname="gmd:pointOfContact">Point of contact</name>
      <name tagname="gmd:polygon">Polygon</name>
      <name tagname="gmd:portrayalCatalogueCitation">Portrayal catalogue citation</name>
      <name tagname="gmd:portrayalCatalogueInfo">Portrayal catalogue info</name>
      <name tagname="gmd:positionName">Position name</name>
      <name tagname="gmd:postalCode">Postal code</name>
      <name tagname="gmd:presentationForm">Presentation form</name>
      <name tagname="gmd:processingLevelCode">Processing level code</name>
      <name tagname="gmd:processor">Processor</name>
      <name tagname="gmd:processStep">Process step</name>
      <name tagname="gmd:propertyType">propertyType</name>
      <name tagname="gmd:protocol">Protocol</name>
      <name tagname="gmd:PT_FreeText">Free text</name>
      <name tagname="gmd:PT_Locale">Locale</name>
      <name tagname="gmd:PT_LocaleContainer">Locale Container</name>
      <name tagname="gmd:purpose">Purpose</name>
      <name tagname="gmd:radiometricCalibrationDataAvailability">Radiometric calibration data availability</name>
      <name tagname="gmd:rationale">Rationale</name>
      <name tagname="gmd:referenceSystemIdentifier">Reference system identifier</name>
      <name tagname="gmd:referenceSystemInfo">Reference system info</name>
      <name tagname="gmd:report">Report</name>
      <name tagname="gmd:resolution">Resolution</name>
      <name tagname="gmd:resourceConstraints">Resource constraints</name>
      <name tagname="gmd:resourceFormat">Resource format</name>
      <name tagname="gmd:resourceMaintenance">Resource maintenance</name>
      <name tagname="gmd:resourceSpecificUsage">Resource specific usage</name>
      <name tagname="gmd:responsibleParty">Responsible Party</name>
      <name tagname="gmd:result">Result</name>
      <name tagname="gmd:role">Role</name>
      <name tagname="gmd:RS_Identifier">RS Identifier</name>
      <name tagname="gmd:rule">Rule</name>
      <name tagname="gmd:scaleDenominator">Scale</name>
      <name tagname="gmd:scaleFactor">Scale factor</name>
      <name tagname="gmd:schemaAscii">Schema ascii</name>
      <name tagname="gmd:schemaLanguage">Schema language</name>
      <name tagname="gmd:scope">Scope</name>
      <name tagname="gmd:sequenceIdentifier">Sequence identifier</name>
      <name tagname="gmd:series">Series</name>
      <name tagname="gmd:seriesMetadata">seriesMetadata</name>
      <name tagname="gmd:shortName">Short name</name>
      <name tagname="gmd:softwareDevelopmentFile">Software development file</name>
      <name tagname="gmd:softwareDevelopmentFileFormat">Software development file format</name>
      <name tagname="gmd:source">Source</name>
      <name tagname="gmd:sourceCitation">Source citation</name>
      <name tagname="gmd:sourceExtent">Source extent</name>
      <name tagname="gmd:sourceReferenceSystem">Source reference system</name>
      <name tagname="gmd:sourceStep">Source step</name>
      <name tagname="gmd:southBoundLatitude">South bound latitude</name>
      <name tagname="gmd:spatialExtent">Spatial extent</name>
      <name tagname="gmd:spatialRepresentationInfo">Spatial representation info</name>
      <name tagname="gmd:spatialRepresentationType">Spatial representation type</name>
      <name tagname="gmd:spatialResolution">Spatial resolution</name>
      <name tagname="gmd:specification">Specification</name>
      <name tagname="gmd:specification">Specification</name>
      <name tagname="gmd:specificUsage">Specific usage</name>
      <name tagname="gmd:statement">Statement</name>
      <name tagname="gmd:status">Status</name>
      <name tagname="gmd:subset">Subset</name>
      <name tagname="gmd:superset">Superset</name>
      <name tagname="gmd:supplementalInformation">Supplemental Information</name>
      <name tagname="gmd:temporalElement">Temporal element</name>
      <name tagname="gmd:textGroup">Text Group</name>
      <name tagname="gmd:thesaurusName">Thesaurus name</name>
      <name tagname="gmd:title">Title</name>
      <name tagname="gmd:toneGradation">Tone gradation</name>
      <name tagname="gmd:topicCategory">Topic category</name>
      <name tagname="gmd:topologyLevel">Topology level</name>
      <name tagname="gmd:transferOptions">Transfer options</name>
      <name tagname="gmd:transferSize">Transfer size</name>
      <name tagname="gmd:transformationDimensionDescription">Transformation dimension description</name>
      <name tagname="gmd:transformationDimensionMapping">Transformation dimension mapping</name>
      <name tagname="gmd:transformationParameterAvailability">Transformation parameter availability</name>
      <name tagname="gmd:triangulationIndicator">Triangulation indicator</name>
      <name tagname="gmd:turnaround">Turnaround</name>
      <name tagname="gmd:type">Type</name>
      <name tagname="gmd:units">Value unit</name>
      <name tagname="gmd:unitsOfDistribution">Units of distribution</name>
      <name tagname="gmd:updateScope">Update scope</name>
      <name tagname="gmd:updateScopeDescription">Update scope description</name>
      <name tagname="gmd:URL">URL</name>
      <name tagname="gmd:usageDateTime">Usage date and time</name>
      <name tagname="gmd:useConstraints">Use constraints</name>
      <name tagname="gmd:useLimitation">Use limitation</name>
      <name tagname="gmd:userContactInfo">User contact info</name>
      <name tagname="gmd:userDefinedMaintenanceFrequency">User defined maintenance frequency</name>
      <name tagname="gmd:userDeterminedLimitations">User determined limitations</name>
      <name tagname="gmd:userNote">User note</name>
      <name tagname="gmd:value">Value</name>
      <name tagname="gmd:valueType">Value type</name>
      <name tagname="gmd:valueUnit">Value unit</name>
      <name tagname="gmd:version">Version</name>
      <name tagname="gmd:verticalCRS">Vertical CRS</name>
      <name tagname="gmd:verticalElement">Vertical element</name>
      <name tagname="gmd:voice">Voice</name>
      <name tagname="gmd:volumes">Volumes</name>
      <name tagname="gmd:westBoundLongitude">West bound longitude</name>
      <!-- === GMI namespace -->
      <name tagname="gmi:AbstractMI_GeolocationInformation">Geolocation Information</name>
      <name tagname="gmi:accuracyReport">Accuracy report</name>
      <name tagname="gmi:acquisitionInformation">Acquisition</name>
      <name tagname="gmi:acquisitionPlan">Acquisition plan</name>
      <name tagname="gmi:acquisitionRequirement">Acquisition requirement</name>
      <name tagname="gmi:algorithm">Algorithm</name>
      <name tagname="gmi:averageAirTemperature">Average air temperature</name>
      <name tagname="gmi:bandBoundaryDefinition">Band boundary definition</name>
      <name tagname="gmi:checkPoint">Check point</name>
      <name tagname="gmi:childOperation">Child operation</name>
      <name tagname="gmi:collectionIdentification">Collection Identification</name>
      <name tagname="gmi:collectionName">Collection name</name>
      <name tagname="gmi:context">Context</name>
      <name tagname="context">Context</name>
      <name tagname="gmi:coordinateReferenceSystem">Coordinate Reference System</name>
      <name tagname="gmi:description">Description</name>
      <name tagname="gmi:definition">Definition</name>
      <name tagname="gmi:detectedPolarisation">Detected polarisation</name>
      <name tagname="gmi:documentation">Documentation</name>
      <name tagname="gmi:environmentalConditions">Environmental conditions</name>
      <name tagname="gmi:expectedObjective">Expected Objective</name>
      <name tagname="gmi:expiryDate">Expiry Date</name>
      <name tagname="gmi:extent">Extent</name>
      <name tagname="gmi:fileType">File Type</name>
      <name tagname="gmi:gcp">GCP</name>
      <name tagname="gmi:geographicCoordinates">Geographic Coordinates</name>
      <name tagname="gmi:geolocationIdentification">Geolocation Identification</name>
      <name tagname="gmi:geolocationInformation">Geolocation Information</name>
      <name tagname="gmi:groundResolution">Ground Resolution</name>
      <name tagname="gmi:identifier">Identifier</name>
      <name tagname="identifier">Identifier</name>
      <name tagname="gmi:instrument">Instrument</name>
      <name tagname="gmi:latestAcceptableDate">Latest Acceptable Date</name>
      <name tagname="gmi:LE_Algorithm">Algorithm</name>
      <name tagname="gmi:LE_NominalResolution">Nominal Resolution</name>
      <name tagname="gmi:LE_Processing">Processing</name>
      <name tagname="gmi:LE_ProcessStep">Process Step</name>
      <name tagname="gmi:LE_ProcessStepReport">Process Step Report</name>
      <name tagname="gmi:LE_Source">Source</name>
      <name tagname="gmi:maxAltitude">Max Altitude</name>
      <name tagname="gmi:maxRelativeHumidity">Max Relative Humidity</name>
      <name tagname="gmi:meteorologicalConditions">Meteorological Conditions</name>
      <name tagname="gmi:MI_AcquisitionInformation">Acquisition Information</name>
      <name tagname="gmi:MI_Band">Band</name>
      <name tagname="gmi:MI_BandDefinition">Band Definition</name>
      <name tagname="gmi:MI_ContextCode">Context Code</name>
      <name tagname="MI_ContextCode">Context Code</name>
      <name tagname="gmi:MI_CoverageDescription">Coverage Description</name>
      <name tagname="gmi:MI_EnvironmentalRecord">Environmental Record</name>
      <name tagname="gmi:MI_Event">Event</name>
      <name tagname="MI_Event">Event</name>
      <name tagname="gmi:MI_GCP">GCP</name>
      <name tagname="gmi:MI_GCPCollection">GCP Collection</name>
      <name tagname="gmi:MI_GeometryTypeCode">Geometry Type Code</name>
      <name tagname="gmi:MI_Georectified">Georectified</name>
      <name tagname="gmi:MI_Georeferenceable">Georeferenceable</name>
      <name tagname="gmi:MI_ImageDescription">Image Description</name>
      <name tagname="gmi:MI_Instrument">Instrument</name>
      <name tagname="gmi:MI_Objective">Objective</name>
      <name tagname="gmi:MI_Metadata">Metadata</name>
      <name tagname="gmi:MI_ObjectiveTypeCode">Objective Type Code</name>
      <name tagname="gmi:MI_Operation">Operation</name>
      <name tagname="MI_Operation">Operation</name>
      <name tagname="gmi:MI_OperationTypeCode">Operation Type Code</name>
      <name tagname="gmi:MI_Plan">Plan</name>
      <name tagname="gmi:MI_Platform">Platform</name>
      <name tagname="gmi:MI_PlatformPass">Platform Pass</name>
      <name tagname="gmi:MI_PolarisationOrientationCode">Polarisation Orientation Code</name>
      <name tagname="gmi:MI_PriorityCode">Priority Code</name>
      <name tagname="gmi:MI_RangeElementDescription">Range Element Description</name>
      <name tagname="gmi:MI_RequestedDate">Requested Date</name>
      <name tagname="gmi:MI_Requirement">Requirement</name>
      <name tagname="gmi:MI_SensorTypeCode">Sensor Type Code</name>
      <name tagname="gmi:MI_SequenceCode">Sequence Code</name>
      <name tagname="MI_SequenceCode">Sequence Code</name>
      <name tagname="gmi:MI_TransferFunctionTypeCode">Transfer Function Type Code</name>
      <name tagname="gmi:MI_TriggerCode">Trigger Code</name>
      <name tagname="MI_TriggerCode">Trigger Code</name>
      <name tagname="gmi:mountedOn">Mounted On</name>
      <name tagname="gmi:name">Name</name>
      <name tagname="gmi:nominalSpatialResolution">Nominal Spatial Resolution</name>
      <name tagname="gmi:objective">Objective</name>
      <name tagname="objective">Objective</name>
      <name tagname="gmi:objectiveOccurance">ObjectiveOccurance</name>
      <name tagname="gmi:operation">Operation Information</name>
      <name tagname="gmi:operation">Operation Information</name>
      <name tagname="gmi:output">Output</name>
      <name tagname="gmi:parentOperation">Parent Operation</name>
      <name tagname="parentOperation">Parent Operation</name>
      <name tagname="gmi:pass">Pass</name>
      <name tagname="gmi:plan">Plan</name>
      <name tagname="gmi:platform">Platform</name>
      <name tagname="gmi:platformParameters">Platform Parameters</name>
      <name tagname="gmi:priority">Priority</name>
      <name tagname="gmi:procedureDescription">Procedure Description</name>
      <name tagname="gmi:processedLevel">Processed Level</name>
      <name tagname="gmi:processingInformation">Processing Information</name>
      <name tagname="gmi:QE_CoverageResult">Coverage Result</name>
      <name tagname="gmi:QE_Usability">Usability</name>
      <name tagname="gmi:qualityInfo">Quality Info</name>
      <name tagname="gmi:rangeElement">Range Element</name>
      <name tagname="gmi:rangeElementDescription">Range Element Description</name>
      <name tagname="gmi:recipient">Recipient</name>
      <name tagname="gmi:relatedEvent">Related Event</name>
      <name tagname="gmi:relatedPass">Related Pass</name>
      <name tagname="gmi:relatedSensor">Related Sensor</name>
      <name tagname="gmi:report">Report</name>
      <name tagname="gmi:requestedDate">Requested Date</name>
      <name tagname="gmi:requestedDateOfCollection">Requested Date of Collection</name>
      <name tagname="gmi:requestor">Requestor</name>
      <name tagname="gmi:resolution">Resolution</name>
      <name tagname="gmi:resultContentDescription">Result Content Description</name>
      <name tagname="gmi:resultFile">Result File</name>
      <name tagname="gmi:resultFormat">Result Format</name>
      <name tagname="gmi:resultSpatialRepresentation">Result Spatial Representation</name>
      <name tagname="gmi:runTimeParameters">Run Time Parameters</name>
      <name tagname="gmi:satisfiedRequirement">Satisfied Requirement</name>
      <name tagname="gmi:satisifiedPlan">Satisified Plan</name>
      <name tagname="gmi:scanningResolution">Scanning Resolution</name>
      <name tagname="gmi:sensingInstrument">Sensing Instrument</name>
      <name tagname="gmi:sequence">Sequence</name>
      <name tagname="sequence">Sequence</name>
      <name tagname="gmi:significantEvent">Significant Event</name>
      <name tagname="significantEvent">Significant Event</name>
      <name tagname="gmi:softwareReference">Software Reference</name>
      <name tagname="gmi:sponsor">Sponsor</name>
      <name tagname="gmi:status">Status</name>
      <name tagname="status">Status</name>
      <name tagname="gmi:time">Time</name>
      <name tagname="time">Time</name>
      <name tagname="gmi:transferFunctionType">Transfer function type</name>
      <name tagname="gmi:transmittedPolarisation">Transmitted polarisation</name>
      <name tagname="gmi:trigger">Trigger</name>
      <name tagname="trigger">Trigger</name>
      <name tagname="gmi:type">Type</name>
      <!-- === GML namespace -->
      <name tagname="gml:a">a</name>
      <name tagname="gml:b">b</name>
      <name tagname="gml:begin">Begin</name>
      <name tagname="gml:beginPosition">Begin date</name>
      <name tagname="gml:c">c</name>
      <name tagname="gml:ConventionalUnit">Conventional unit</name>
      <name tagname="gml:conversionToPreferredUnit">Conversion to preferred unit</name>
      <name tagname="gml:coordinates">Coordinates</name>
      <name tagname="gml:description">Description</name>
      <name tagname="gml:end">End</name>
      <name tagname="gml:endPosition">End date</name>
      <name tagname="gml:exterior">Outer boundary</name>
      <name tagname="gml:formula">Formula</name>
      <name tagname="gml:id">Identifier</name>
      <name tagname="gml:identifier">Identifier</name>
      <name tagname="gml:interior">Inner boundary</name>
      <name tagname="gml:LinearRing">Linear ring</name>
      <name tagname="gml:LineString">Line</name>
      <name tagname="gml:Point">Point</name>
      <name tagname="gml:Polygon">Polygon</name>
      <name tagname="gml:relatedTime">Related time</name>
      <name tagname="gml:TimeInstant">Time instant</name>
      <name tagname="gml:TimePeriod">Time period</name>
      <name tagname="gml:timePosition">Time position</name>
      <name tagname="gml:BaseUnit">Base unit</name>
      <name tagname="gml:unitsSystem">Units system</name>
      <!-- All XML attributes declared in the GML schema are defined without namespace, the only exception is the gml:id XML attribute. -->
      <name tagname="srsName">Spatial Reference System Name</name>
      <!-- === SRV namespace for 19119 service metadata -->
      <name tagname="srv:SV_ServiceIdentification">Service Identification (19119)</name>
      <name tagname="srv:serviceType">Service Type</name>
      <name tagname="srv:serviceTypeVersion">Service Version</name>
      <name tagname="srv:accessProperties">Access Properties</name>
      <name tagname="srv:restrictions">Restrictions</name>
      <name tagname="srv:containsOperations">Contains Operations</name>
      <name tagname="srv:operatesOn">Operates On</name>
      <name tagname="srv:operationName">Operation Name</name>
      <name tagname="srv:SV_OperationMetadata">Operation</name>
      <name tagname="srv:DCP">Distributed Computing Platforms</name>
      <name tagname="srv:DCPList">Distributed Computing Platforms List</name>
      <name tagname="srv:operationDescription">Operation Description</name>
      <name tagname="srv:invocationName">Invocation Name</name>
      <name tagname="srv:parameters">Parameters</name>
      <name tagname="srv:connectPoint">Connect Point</name>
      <name tagname="srv:dependsOn">Depends On</name>
      <name tagname="srv:providerName">Provider Name</name>
      <name tagname="srv:serviceContact">Service Contact</name>
      <name tagname="srv:name">Name</name>
      <name tagname="srv:description">Description</name>
      <name tagname="srv:optionality">Optionality</name>
      <name tagname="srv:repeatability">Repeatability</name>
      <name tagname="srv:coupledResource">Coupled Resource</name>
      <name tagname="srv:SV_CoupledResource">Coupled Resource</name>
      <name tagname="srv:identifier">Identifier</name>
      <name tagname="srv:couplingType">Coupling Type</name>
      <name tagname="srv:SV_CouplingType">Coupling Type</name>
      <name tagname="srv:extent">Extent</name>
      <name tagname="srv:keywords">Keywords</name>
      <!-- === GCO namespace -->
      <!--
		<name tagname="gco:CharacterString">Character String</name>
		<name tagname="gco:Date">Date</name>
		<name tagname="gco:DateTime">Date and time</name>
		<name tagname="gco:Measure">Measure</name>
	-->
      <!-- === GTS namespace                                    -->
      <name tagname="gts:TM_PeriodDuration">Period duration</name>
      <!-- === GMX namespace                                    -->
      <name tagname="gmx:Anchor">Anchor</name>
      <name tagname="gmx:name">Name</name>
      <name tagname="gmx:scope">Scope</name>
      <name tagname="gmx:versionNumber">Version number</name>
      <name tagname="gmx:versionDate">Version date</name>
      <name tagname="gmx:language">Language</name>
      <name tagname="gmx:characterSet">Character set</name>
      <name tagname="gmx:FileName">File Name</name>
      <name tagname="gmx:MX_ScopeCode">MX_ScopeCode</name>
      <name tagname="gmx:MimeFileType">Mime File Type</name>
      <!-- === Biological Extensions                              -->
      <name tagname="gmd:taxonomy">Taxonomy</name>
      <name tagname="gmd:MD_TaxonSys">Taxonomic System</name>
      <name tagname="gmd:classSys">Classification System Authority</name>
      <name tagname="gmd:classmod">Classification System Modifications</name>
      <name tagname="gmd:taxongen">General Taxonomic Scope</name>
      <name tagname="gmd:idref">Identification Reference</name>
      <name tagname="gmd:obs">Observer</name>
      <name tagname="gmd:taxonpro">Taxonomic Procedures</name>
      <name tagname="gmd:taxoncom">Taxonomic Completeness</name>
      <name tagname="gmd:voucher">Voucher Information</name>
      <name tagname="gmd:MD_Vouchers">Vouchers</name>
      <name tagname="gmd:specimen">Specimen</name>
      <name tagname="gmd:reposit">Repository</name>
      <name tagname="gmd:taxonCl">Taxonomic Classification Information</name>
      <name tagname="gmd:MD_TaxonCl">Taxonomic Classification</name>
      <name tagname="gmd:common">Common Name</name>
      <name tagname="gmd:taxonrn">Taxonomic Rank Name</name>
      <name tagname="gmd:taxonrv">Taxonomic Rank Value</name>
      <name tagname="gmd:hiclass">Hierarchical Classification</name>
      <!--===GFC namespace-->
      <name tagname="gfc:FC_FeatureCatalogue">Feature Catalogue</name>
      <name tagname="gfc:featureType">Feature Type Information</name>
      <name tagname="gfc:FC_FeatureType">Feature type</name>
      <name tagname="gfc:typeName">Type name</name>
      <name tagname="gfc:definition">Definition</name>
      <name tagname="gfc:isAbstract">Is abstract</name>
      <name tagname="gfc:featureCatalogue">Feature Catalogue Information</name>
      <name tagname="gfc:carrierOfCharacteristics">Carrier of characteristics</name>
      <name tagname="gfc:FC_FeatureAttribute">Feature attribute</name>
      <name tagname="gfc:memberName">Member name</name>
      <name tagname="gfc:cardinality">Cardinality</name>
      <name tagname="gfc:definitionReference">Definition Reference Information</name>
      <name tagname="gfc:FC_DefinitionReference">Definition reference</name>
      <name tagname="gfc:definitionSource">Definition Source Information</name>
      <name tagname="gfc:FC_DefinitionSource">Definition source</name>
      <name tagname="gfc:source">Source</name>
      <name tagname="gfc:valueMeasurementUnit">Value measurement unit</name>
      <name tagname="gfc:constrainedBy">Constrained by</name>
      <name tagname="gfc:FC_Constraint">Constraint</name>
      <name tagname="gfc:description">Description</name>
      <name tagname="gfc:producer">Producer</name>
      <name tagname="gfc:listedValue">Listed value</name>
      <name tagname="gfc:FC_ListedValue">Listed Value</name>
      <name tagname="gfc:label">Label</name>
    </names>
  </xsl:variable>
  <xsl:variable name="g-header-translations">
    <names>
      <name tagname="gmd:spatialRepresentationInfo">Spatial Representation Information</name>
      <name tagname="gmd:referenceSystemInfo">Reference System Information</name>
      <name tagname="gmd:identificationInfo">Identification Information</name>
      <name tagname="gmd:contentInfo">Content Information</name>
      <name tagname="gmd:distributionInfo">Distribution Information</name>
      <name tagname="gmd:dataQualityInfo">Data Quality Information</name>
      <name tagname="gmd:portrayalCatalogueInfo">Portrayal Catalogue Information</name>
      <name tagname="gmd:metadataConstraints">Metadata Constraint Information</name>
      <name tagname="gmd:applicationSchemaInfo">Application Schema Information</name>
      <name tagname="gmd:metadataMaintenance">Metadata Maintenance Information</name>
      <name tagname="gmi:acquisitionInformation">Acquisition Information</name>
      <name tagname="gmd:metadataExtensionInfo">Metadata Extension Information</name>
      <name tagname="gfc:FC_FeatureCatalogue">Feature Catalog Information</name>
    </names>
  </xsl:variable>
  <!-- Templates -->
  <xsl:template match="/">
    <html>
      <body>
        <font size="+3">
          <xsl:element name="a">
            <xsl:attribute name="name">
              <xsl:value-of select="'title'"/>
            </xsl:attribute>
            <xsl:value-of select="//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString"/>
          </xsl:element>
        </font>
        <font size="+3">
          <xsl:element name="a">
            <xsl:attribute name="name">
              <xsl:value-of select="'title'"/>
            </xsl:attribute>
            <xsl:value-of select="//gmd:identificationInfo/srv:SV_ServiceIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString"/>
          </xsl:element>
        </font>
        <br/>
        <br/>
        <xsl:for-each select="./*/*">
          <xsl:variable name="transname" select="name()"/>
          <xsl:if test="contains($transname,'gmd:spatialRepresentationInfo') or contains($transname,'gmd:referenceSystemInfo') or contains($transname,'gmd:metadataExtensionInfo') or contains($transname,'gmd:identificationInfo') or contains($transname,'gmd:contentInfo') or contains($transname,'gmd:distributionInfo') or contains($transname,'gmd:dataQualityInfo') or contains($transname,'gmd:portrayalCatalogueInfo') or contains($transname,'gmd:metadataConstraints') or contains($transname,'gmd:applicationSchemaInfo') or contains($transname,'gmd:metadataMaintenance') or contains($transname,'gmd:metadataMaintenanceInfo') or contains($transname,'gmi:acquisitionInformation') or contains($transname,'gfc:FC_FeatureCatalogue')">
            <xsl:element name="a">
              <xsl:attribute name="href">
                <xsl:value-of select="'#'"/>
                <xsl:value-of select="substring-after($transname,':')"/>
              </xsl:attribute>
              <span style="text-transform: capitalize;">
                <xsl:apply-templates select="child::title" mode="outIt"/>
                <xsl:value-of select="exsl:node-set($g-header-translations)/*/name[@tagname=$transname]"/>
              </span>
            </xsl:element>
            <br/>
          </xsl:if>
        </xsl:for-each>
        <hr/>
        <pre>
          <xsl:apply-templates select="*"/>
          <xsl:element name="a">
            <xsl:attribute name="href">
              <xsl:value-of select="'#title'"/>
            </xsl:attribute>
            <div align="left">Return To Index</div>
          </xsl:element>
        </pre>
      </body>
    </html>
  </xsl:template>
  <!--
  Apply to all elements. Determine whether it's a compound or text element
  and call the appropriate template.
-->
  <xsl:template match="*">
    <xsl:param name="indent" select="''"/>
    <xsl:param name="indent-increment" select="$g-indent-increment"/>
    <xsl:variable name="tagname" select="name()"/>
    <xsl:variable name="tag-longname" select="exsl:node-set($g-tag-translations)/*/name[@tagname=$tagname]"/>
    <xsl:variable name="tag-translation">
      <!-- Display long name if we can translate the tag, else just display the tag name itself -->
      <xsl:choose>
        <xsl:when test="$tag-longname">
          <xsl:value-of select="$tag-longname"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="$tagname"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:variable name="output">
      <!-- do not output element names w/ gco namespaces -->
      <xsl:if test="not(contains($tag-translation, 'gco'))">
        <xsl:value-of select="concat($indent, $tag-translation, ': ')"/>
      </xsl:if>
    </xsl:variable>
    <xsl:if test="string-length(normalize-space($tag-translation)) &gt; 0">
      <xsl:choose>
        <xsl:when test="count(ancestor::*) = 1 ">
          <xsl:choose>
            <xsl:when test="contains($tagname,'gmd:spatialRepresentationInfo') or contains($tagname,'gmd:referenceSystemInfo') or contains($tagname,'gmd:metadataExtensionInfo') or contains($tagname,'gmd:identificationInfo') or contains($tagname,'gmd:contentInfo') or contains($tagname,'gmd:distributionInfo') or contains($tagname,'gmd:dataQualityInfo') or contains($tagname,'gmd:portrayalCatalogueInfo') or contains($tagname,'gmd:metadataConstraints') or contains($tagname,'gmd:applicationSchemaInfo') or contains($tagname,'gmd:metadataMaintenance') or contains($tagname,'gmd:metadataMaintenanceInfo') or contains($tagname,'gmi:acquisitionInformation') or contains($tagname,'gfc:FC_FeatureCatalogue')">
              <xsl:if test="(position()&gt;1)">
                <xsl:element name="a">
                  <xsl:attribute name="href">
                    <xsl:value-of select="'#title'"/>
                  </xsl:attribute>
                  <div align="left">Return To Index</div>
                </xsl:element>
                <hr/>
              </xsl:if>
              <b>
                <xsl:element name="a">
                  <xsl:attribute name="name">
                    <xsl:value-of select="substring-after($tagname,':')"/>
                  </xsl:attribute>
                  <xsl:value-of select="$output"/>
                </xsl:element>
              </b>
            </xsl:when>
            <xsl:otherwise>
              <b>
                <xsl:value-of select="$output"/>
              </b>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:when>
        <xsl:otherwise>
          <b>
            <xsl:value-of select="$output"/>
          </b>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:if>
    <xsl:choose>
      <xsl:when test="*">
        <!-- This is a compound element (i.e., it has children) -->
        <xsl:choose>
          <xsl:when test="string-length(normalize-space($tag-translation)) &gt; 0">
            <xsl:call-template name="printAttributes"/>
            <!-- There is a tag translation -->
            <xsl:value-of select="$newline"/>
            <xsl:apply-templates select="*">
              <xsl:with-param name="indent" select="concat($indent, $indent-increment)"/>
            </xsl:apply-templates>
          </xsl:when>
          <xsl:otherwise>
            <!-- No tag translation -->
            <xsl:apply-templates select="*">
              <xsl:with-param name="indent" select="concat($indent, $indent-increment)"/>
            </xsl:apply-templates>
          </xsl:otherwise>
        </xsl:choose>
      </xsl:when>
      <!-- else a content element: display the text -->
      <xsl:otherwise>
        <xsl:call-template name="printAttributes"/>
        <!-- if tag name has gco namespace - do not add a new line-->
        <xsl:if test="not(contains($tag-translation,'gco'))">
          <xsl:value-of select="$newline"/>
        </xsl:if>
        <!-- Call the imported printFormatted template to print both
            preformatted text and word-wrapped paragraphs.
            This will parse each line, and call back to the
            printFormattedLine and printParagraphLine templates
            in this file. -->
        <xsl:call-template name="printFormatted">
          <xsl:with-param name="elementContent">
            <!-- strip leading whitespace only from first line of text -->
            <xsl:call-template name="strip-leading-whitespace">
              <!-- display element attributes OR content (note: not all attributes are included for translation-->
              <xsl:with-param name="content" select="@codeListValue|@gco:nilReason|@indeterminatePosition|node()"/>
            </xsl:call-template>
          </xsl:with-param>
          <xsl:with-param name="startFormattedSectionString" select="''"/>
          <!-- nothing needed -->
          <xsl:with-param name="endFormattedSectionString" select="''"/>
          <!-- nothing needed -->
          <xsl:with-param name="optional-param-1" select="concat($indent, $indent-increment)"/>
          <xsl:with-param name="optional-param-2" select="number($g-fold-width) - string-length($indent)"/>
        </xsl:call-template>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  <xsl:template name="printAttributes">
    <xsl:choose>
      <xsl:when test="./@*">
        <xsl:if test="./@uuid">
          <xsl:value-of select="concat('uuid: ', @uuid)"/>
        </xsl:if>
        <xsl:if test="./@uuidref">
          <xsl:value-of select="concat('uuidref: ', @uuidref)"/>
        </xsl:if>
        <xsl:if test="./@uom">
          <xsl:value-of select="concat('uom: ', @uom)"/>
        </xsl:if>
        <xsl:if test="./@xlink:href">
          <xsl:value-of select="concat('xlink: ', @xlink:href)"/>
        </xsl:if>
        <xsl:if test="./@xlink:title">
          <xsl:value-of select="concat(' title: ', @xlink:title)"/>
        </xsl:if>
        <!--<xsl:if test="./@codeListValue"> (<xsl:value-of select="concat('codeListValue: ', @codeListValue)"/>)</xsl:if>-->
        <xsl:if test="./@locale">
          <xsl:value-of select="concat('locale: ', @locale)"/>
        </xsl:if>
      </xsl:when>
    </xsl:choose>
  </xsl:template>
  <!--
  Text formatting template. Use existing line breaks. Indent each line
  to the current indent level. Return the next line each time the template
  is called.
  -->
</xsl:stylesheet>
