from enum import Enum

# Vendored classes from the ArcGIS SDK for Python package, version 2.4.1.
# See docs/libraries.md for more information.


class ItemType(Enum):
    """
    ArcGIS item type.

    Original import: `arcgis.gis._impl._dataclasses._contentds.ItemTypeEnum`
    """

    DATA_STORE = "Data Store"
    VR_EXPERIENCE = "360 VR Experience"
    CITYENGINE_WEB_SCENE = "CityEngine Web Scene"
    MAP_AREA = "Map Area"
    PRO_MAP = "Pro Map"
    WEB_MAP = "Web Map"
    WEB_SCENE = "Web Scene"
    FEATURE_COLLECTION = "Feature Collection"
    FEATURE_COLLECTION_TEMPLATE = "Feature Collection Template"
    FEATURE_SERVICE = "Feature Service"
    GEODATA_SERVICE = "Geodata Service"
    GLOBE_SERVICE = "Globe Service"
    IMAGE_SERVICE = "Image Service"
    KML = "KML"
    KML_COLLECTION = "KML Collection"
    MAP_SERVICE = "Map Service"
    OGCFEATURESERVER = "OGCFeatureServer"
    ORIENTED_IMAGERY_CATALOG = "Oriented Imagery Catalog"
    RELATIONAL_DATABASE_CONNECTION = "Relational Database Connection"
    SCENE_SERVICE = "Scene Service"
    VECTOR_TILE_SERVICE = "Vector Tile Service"
    WFS = "WFS"
    WMS = "WMS"
    WMTS = "WMTS"
    GEOMETRY_SERVICE = "Geometry Service"
    GEOCODING_SERVICE = "Geocoding Service"
    GEOPROCESSING_SERVICE = "Geoprocessing Service"
    NETWORK_ANALYSIS_SERVICE = "Network Analysis Service"
    WORKFLOW_MANAGER_SERVICE = "Workflow Manager Service"
    APPBUILDER_EXTENSION = "AppBuilder Extension"
    APPBUILDER_WIDGET_PACKAGE = "AppBuilder Widget Package"
    CODE_ATTACHMENT = "Code Attachment"
    DASHBOARD = "Dashboard"
    DEEP_LEARNING_STUDIO_PROJECT = "Deep Learning Studio Project"
    ESRI_CLASSIFICATION_SCHEMA = "Esri Classification Schema"
    EXCALIBUR_IMAGERY_PROJECT = "Excalibur Imagery Project"
    EXPERIENCE_BUILDER_WIDGET = "Experience Builder Widget"
    EXPERIENCE_BUILDER_WIDGET_PACKAGE = "Experience Builder Widget Package"
    FORM = "Form"
    APPLICATION = "Application"
    API_KEY_CREDENTIALS = "Application"
    GEOBIM_APPLICATION = "GeoBIM Application"
    GEOBIM_PROJECT = "GeoBIM Project"
    HUB_EVENT = "Hub Event"
    HUB_INITIATIVE = "Hub Initiative"
    HUB_INITIATIVE_TEMPLATE = "Hub Initiative Template"
    HUB_PAGE = "Hub Page"
    HUB_PROJECT = "Hub Project"
    HUB_SITE_APPLICATION = "Hub Site Application"
    INSIGHTS_WORKBOOK = "Insights Workbook"
    INSIGHTS_WORKBOOK_PACKAGE = "Insights Workbook Package"
    INSIGHTS_MODEL = "Insights Model"
    INSIGHTS_PAGE = "Insights Page"
    INSIGHTS_THEME = "Insights Theme"
    INSIGHTS_DATA_ENGINEERING_WORKBOOK = "Insights Data Engineering Workbook"
    INSIGHTS_DATA_ENGINEERING_MODEL = "Insights Data Engineering Model"
    INVESTIGATION = "Investigation"
    MISSION = "Mission"
    MOBILE_APPLICATION = "Mobile Application"
    NOTEBOOK = "Notebook"
    NATIVE_APPLICATION = "Native Application"
    NATIVE_APPLICATION_INSTALLER = "Native Application Installer"
    OPERATION_VIEW = "Operation View"
    OPERATIONS_DASHBOARD_ADD_IN = "Operations Dashboard Add In"
    OPERATIONS_DASHBOARD_EXTENSION = "Operations Dashboard Extension"
    ORTHO_MAPPING_PROJECT = "Ortho Mapping Project"
    ORTHO_MAPPING_TEMPLATE = "Ortho Mapping Template"
    SOLUTION = "Solution"
    STORYMAP = "StoryMap"
    WEB_APPBUILDER_WIDGET = "Web AppBuilder Widget"
    WEB_EXPERIENCE = "Web Experience"
    WEB_EXPERIENCE_TEMPLATE = "Web Experience Template"
    WEB_MAPPING_APPLICATION = "Web Mapping Application"
    WORKFORCE_PROJECT = "Workforce Project"
    ADMINISTRATIVE_REPORT = "Administrative Report"
    APACHE_PARQUET = "Apache Parquet"
    CAD_DRAWING = "CAD Drawing"
    COLOR_SET = "Color Set"
    CONTENT_CATEGORY_SET = "Content Category Set"
    CSV = "CSV"
    DOCUMENT_LINK = "Document Link"
    EARTH_CONFIGURATION = "Earth configuration"
    ESRI_CLASSIFIER_DEFINITION = "Esri Classifier Definition"
    EXPORT_PACKAGE = "Export Package"
    FILE_GEODATABASE = "File Geodatabase"
    GEOJSON = "GeoJson"
    GEOPACKAGE = "GeoPackage"
    GML = "GML"
    IMAGE = "Image"
    IWORK_KEYNOTE = "iWork Keynote"
    IWORK_NUMBERS = "iWork Numbers"
    IWORK_PAGES = "iWork Pages"
    MICROSOFT_EXCEL = "Microsoft Excel"
    MICROSOFT_POWERPOINT = "Microsoft Powerpoint"
    MICROSOFT_WORD = "Microsoft Word"
    PDF = "PDF"
    REPORT_TEMPLATE = "Report Template"
    SERVICE_DEFINITION = "Service Definition"
    SHAPEFILE = "Shapefile"
    SQLITE_GEODATABASE = "SQLite Geodatabase"
    STATISTICAL_DATA_COLLECTION = "Statistical Data Collection"
    STORYMAP_THEME = "StoryMap Theme"
    STYLE = "Style"
    SYMBOL_SET = "Symbol Set"
    VISIO_DOCUMENT = "Visio Document"
    ARCPAD_PACKAGE = "ArcPad Package"
    COMPACT_TILE_PACKAGE = "Compact Tile Package"
    EXPLORER_LAYER = "Explorer Layer"
    IMAGE_COLLECTION = "Image Collection"
    LAYER = "Layer"
    LAYER_PACKAGE = "Layer Package"
    PRO_REPORT = "Pro Report"
    SCENE_PACKAGE = "Scene Package"
    MOBILE_SCENE_PACKAGE = "Mobile Scene Package"
    PROJECT_PACKAGE = "Project Package"
    PROJECT_TEMPLATE = "Project Template"
    PUBLISHED_MAP = "Published Map"
    SCENE_DOCUMENT = "Scene Document"
    TASK_FILE = "Task File"
    TILE_PACKAGE = "Tile Package"
    VECTOR_TILE_PACKAGE = "Vector Tile Package"
    WINDOWS_MOBILE_PACKAGE = "Windows Mobile Package"
    DESKTOP_STYLE = "Desktop Style"
    ARCGIS_PRO_CONFIGURATION = "ArcGIS Pro Configuration"
    DEEP_LEARNING_PACKAGE = "Deep Learning Package"
    GEOPROCESSING_PACKAGE = "Geoprocessing Package"
    GEOPROCESSING_PACKAGE_PRO_VERSION = "Geoprocessing Package (Pro version)"
    GEOPROCESSING_SAMPLE = "Geoprocessing Sample"
    LOCATOR_PACKAGE = "Locator Package"
    RASTER_FUNCTION_TEMPLATE = "Raster function template"
    RULE_PACKAGE = "Rule Package"
    ARCGIS_PRO_ADD_IN = "ArcGIS Pro Add In"
    CODE_SAMPLE = "Code Sample"
    DESKTOP_ADD_IN = "Desktop Add In"
    DESKTOP_APPLICATION = "Desktop Application"
    DESKTOP_APPLICATION_TEMPLATE = "Desktop Application Template"
    EXPLORER_ADD_IN = "Explorer Add In"
    SURVEY123_ADD_IN = "Survey123 Add In"
    WORKFLOW_MANAGER_PACKAGE = "Workflow Manager Package"
    TILES_SERVICE_3D = "3DTiles Service"
    TILES_PACKAGE_3D = "3DTiles Package"
    MOBILE_BASEMAP_PACKAGE = "Mobile Basemap Package"
    MOBILE_MAP_PACKAGE = "Mobile Map Package"


class MetadataFormat(Enum):
    """
    ArcGIS item metadata model.

    Original import: `arcgis.gis._impl._dataclasses._contentds.MetadataFormatEnum`
    """

    FGDB = "fgdb"
    INSPIRE = "inspire"
    ISO19139 = "iso19139"
    ISO19139_32 = "iso19139-3.2"
    ISO19115 = "iso19115"


class SharingLevel(Enum):
    """
    Sharing level for an `Item`.

    Original import: `arcgis.gis._impl._content_manager.sharing.api.SharingLevel`
    """

    ORG = "ORGANIZATION"
    PRIVATE = "PRIVATE"
    EVERYONE = "EVERYONE"
